---
title: "Project 3 - Spatial"
author: "Amir Ahmed"
date: "11 4 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(geoR)
```


```{r}
seismic <- read.csv("seismic.dat", header = F)
seismic <- as.data.frame(seismic)
names(seismic) <- c("d")
seismic$x <- 0:(nrow(seismic)-1) %/% 75 + 1
seismic$y <- 0:(nrow(seismic)-1)%% 75 + 1


complit <- read.csv("complit.dat")

```


```{r}
# Figure 1
topo.li <- interp(seismic$x, seismic$y, seismic$d)
image.plot(topo.li, main = "Display of seismic data, LD", horizontal = T, legend.lab = "d")
contour(topo.li,add=T)

```

```{r}
#1b
# Calculating pi-s from data. 
pi <- dnorm(seismic$d, mean = 0.08, sd = 0.06)/(dnorm(seismic$d, mean = 0.02, sd = 0.06) + dnorm(seismic$d, mean = 0.08, sd = 0.06))
topo.li <- interp(seismic$x, seismic$y, pi)
image.plot(topo.li, main = "Display of probabilies, LD", horizontal = T, legend.lab = "p")
contour(topo.li,add=T)

```

```{r}
par(oma = c(4, 1, 1, 1))

simulate.unif <- function(){
  sapply(pi, function(p) rbinom(n = 1, size = 1, prob = p))
}

par(mfrow=c(3,2))
set.seed(1)
for(i in 1:6){
  sim.res <- simulate.unif()
  topo.li <- interp(seismic$x, seismic$y, sim.res)
  image(topo.li, main = paste0("Simulation ", i), nlevel = 2, col = c("#F7F396", "purple"))
}
par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
legend("bottom", c("Sand", "Shale"), xpd = TRUE, horiz = TRUE, inset = c(0, 
    0), bty = "n", fill = c("#F7F396", "purple"), cex = 2)

```

```{r}
# IB MMAP expectance and variance.
ex <- pi 
var <- pi*(1-pi)
MMAP <- pi >= 0.5
MMAP <- as.numeric(MMAP)

par(mfrow=c(3,1))
topo.li <- interp(seismic$x, seismic$y, ex)
image.plot(topo.li, main = "Expectance, LD", horizontal = F, legend.lab = "Expectance")
contour(topo.li,add=T)

topo.li <- interp(seismic$x, seismic$y, var)
image.plot(topo.li, main = "Variance, LD", horizontal = F, legend.lab = "Variance")
contour(topo.li,add=T)
 

topo.li <- interp(seismic$x, seismic$y, MMAP)
image(topo.li, main = "MMAP", nlevel = 2, col = c("#F7F396", "purple"))
legend("bottom", c("Sand", "Shale"), xpd = TRUE, horiz = TRUE, inset = c(0, 
    0), bty = "n", fill = c("#F7F396", "purple"), cex = 2)


```


